name: Schedule Fetch

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every two minutes #'0 */6 * * *'  # Run every 6 hours
    workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run scheduledFetch.js
      run: node scheduledFetch.js
